name: The name of your action here
description: Provide a description here
author: Your name or organization here

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: heart
  color: red

# Define your inputs here.
inputs:
  milliseconds:
    description: Your input description here
    required: true
    default: '1000'
  tapis_app_spec:
    description: |
      Path to the Tapis application specification JSON file.
      This file should follow the Tapis application specification format.
      Must be a valid path to a .json file that exists in the repository.
      Example: './specs/app-spec.json'
    required: true
    default: '__fixtures__/app.json'

# Define your outputs here.
outputs:
  time:
    description: Your output description here

runs:
  using: node20
  main: dist/index.js
